"""In-app delta updater (Phase 6).

Updates ship as GitHub release assets. The updater compares the local
``manifest.json`` (every file + SHA-256, generated by CI at build time)
against the newest release manifest, downloads **only the changed files**
(the ``delta-v<old>-to-v<new>.zip`` asset) or, when a delta is impossible,
the full portable zip, verifies every byte against the new manifest, and
stages the result for an atomic swap on restart.

Threading contract: :class:`UpdateService` is fully synchronous and
UI-free; :mod:`app.updater.worker` wraps it in a ``QThread`` for the UI.
Network access is injected (:class:`~app.updater.github.ReleaseFetcher`)
so tests never touch the network.
"""

from __future__ import annotations

from app.updater.manifest import (
    FileEntry,
    ManifestDiff,
    build_manifest,
    diff_manifests,
    load_manifest,
    verify_tree,
)
from app.updater.service import (
    REPO_SLUG,
    UpdatePlan,
    UpdaterError,
    UpdateService,
)

__all__ = [
    "REPO_SLUG",
    "FileEntry",
    "ManifestDiff",
    "UpdatePlan",
    "UpdateService",
    "UpdaterError",
    "build_manifest",
    "diff_manifests",
    "load_manifest",
    "verify_tree",
]
